name: simple_carte
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/Asmaa.jpg

  fonts:
    - family: Shantell Sans
      fonts:
        - asset: fonts/ShantellSans-Regular.ttf